# -*- coding: utf-8 -*-
"""Graph.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17s0FXuA39UdrwNmFAY7FwVusLMMpm5kc
"""

class Node:
  def __init__(self, data):
    self.data = data
    self.neighbors = []
    self.visited = False
    
  def add_neighbor(self, neighbor):
    self.neighbors.append(neighbor)

  def set_visited(self, visited):
    self.visited = visited

  def get_data(self):
    return self.data

  def get_neighbors(self):
    return self.neighbors

  def get_visited(self):
    return self.visited


class Graph:
  def __init__(self):
    self.nodes = []

  def add_node(self, node):
    self.nodes.append(node)
    
  def bfs(self):
      if len(self.nodes) > 0:
          for node in self.nodes:
              node.set_visited(False)
              
      queue = []
      self.nodes[2].set_visited(True)
      print(self.nodes[2].get_data(),end="")
      queue.append(self.nodes[2])
      while len(queue) > 0:
          
          current = queue.pop(0)
          neighbors = current.get_neighbors()
          for neighbor in neighbors:
              if not neighbor.get_visited():
                  neighbor.set_visited(True)
                  print("-",neighbor.get_data(),end="")
                  queue.append(neighbor)
      print("")
                      
  def dfs(self):
      if len(self.nodes)>0:
          for node in self.nodes:
              node.set_visited(False)
              
      stack = []
      self.nodes[0].set_visited(True)
      print(self.nodes[0].get_data(),end="")
      stack.append(self.nodes[0])
      while len(stack) > 0:
          neighbors = stack[len(stack)-1].get_neighbors()
          for neighbor in neighbors:
              if not neighbor.get_visited():
                  neighbor.set_visited(True)
                  print("-",neighbor.get_data(),end="")
                  stack.append(neighbor)
                  break
              else:
                  stack.pop(len(stack)-1)
      print("")    
          
       
      
      
      
      
      
      
            
              
              
          


graph = Graph()

node_A = Node('A')
graph.add_node(node_A)
node_B = Node('B')
graph.add_node(node_B)
node_C = Node('C')
graph.add_node(node_C)
node_D = Node('D')
graph.add_node(node_D)
node_E = Node('E')
graph.add_node(node_E)
node_F = Node('F')
graph.add_node(node_F)
node_G = Node('G')
graph.add_node(node_G)
node_H = Node('H')
graph.add_node(node_H)
node_S = Node('S')
graph.add_node(node_S)

node_A.add_neighbor(node_B)
node_A.add_neighbor(node_S)

node_B.add_neighbor(node_A)

node_C.add_neighbor(node_D)
node_C.add_neighbor(node_E)
node_C.add_neighbor(node_F)
node_C.add_neighbor(node_G)
node_C.add_neighbor(node_S)

node_D.add_neighbor(node_C)

node_E.add_neighbor(node_C)
node_E.add_neighbor(node_H)

node_F.add_neighbor(node_C)
node_F.add_neighbor(node_G)

node_G.add_neighbor(node_F)
node_G.add_neighbor(node_S)

node_H.add_neighbor(node_E)
node_H.add_neighbor(node_G)

node_S.add_neighbor(node_A)
node_S.add_neighbor(node_C)
node_S.add_neighbor(node_G)

print("[BFS result]")
graph.bfs()

print("DFs")
graph.dfs()